---
- hosts: myserver
  become: true
  roles:
    - geerlingguy.docker
#    - DavidWittman.redis
#    - franklinkim.mongodb
#    - cmprescott.chrome
#    - jdauphant.sublimetext
#    - gantsign.atom
#    - softasap.sa-neo4j

