---

- name: Configuring database directory
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_user }}"
    mode: "0755"
  with_items:
    - "{{ mongodb_conf.storage.dbPath }}"
    - "{{ mongodb_conf.systemLog.path | dirname }}"
    - "{{ mongodb_conf.processManagement.pidFilePath | dirname }}"

- name: Configuring mongodb
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    backup: yes
    owner: root
    group: root
    mode: "0644"
  notify: restart mongodb
  with_items:
    - etc/logrotate.d/mongodb
    - etc/mongod.conf
