---

- import_tasks: install.yml
  tags:
    - database:nosql
    - mongodb
    - install
    - mongodb-install

- import_tasks: config.yml
  tags:
    - database:nosql
    - mongodb
    - config
    - mongodb-config

- import_tasks: service.yml
  tags:
    - database:nosql
    - mongodb
    - service
    - mongodb-service
